name: Deployment on Dockerhub

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Docker Buildx âŒ
          uses: docker/setup-buildx-action@v1
        
        - name: Login to Docker Hub ğŸ”
          run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

        - name: Build and push Docker image ğŸ—ï¸
          run: |
            docker buildx create --use
            docker buildx build \
            --file Dockerfile \
            --tag safwanshamsir/tutorial-deployment:latest \
            --push .

        env:
            DOCKER_CLI_EXPERIMENTAL: enabled
            DOCKER_BUILDKIT: 1